// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIrfxMisOQzjVJItDDrj5Xc_Gg1oxQs1M',
    appId: '1:247506027549:web:470b8944260cabbbbb72f4',
    messagingSenderId: '247506027549',
    projectId: 'flutter-39755',
    authDomain: 'flutter-39755.firebaseapp.com',
    storageBucket: 'flutter-39755.appspot.com',
    measurementId: 'G-P646RDJMJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe0UkPXNkPwrTWB8UWVSAweRrsv1kNOPE',
    appId: '1:247506027549:android:7b45167501a74c6bbb72f4',
    messagingSenderId: '247506027549',
    projectId: 'flutter-39755',
    storageBucket: 'flutter-39755.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-G3PtM8ybuV59iTe8pbtdnXcSSVtfqdg',
    appId: '1:247506027549:ios:4e526ff3c406dd57bb72f4',
    messagingSenderId: '247506027549',
    projectId: 'flutter-39755',
    storageBucket: 'flutter-39755.appspot.com',
    iosBundleId: 'com.example.ashtarProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-G3PtM8ybuV59iTe8pbtdnXcSSVtfqdg',
    appId: '1:247506027549:ios:0ef95a0d47928e75bb72f4',
    messagingSenderId: '247506027549',
    projectId: 'flutter-39755',
    storageBucket: 'flutter-39755.appspot.com',
    iosBundleId: 'com.example.ashtarProject.RunnerTests',
  );
}
